name: Rajasthan Tender Scraper
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install selenium webdriver-manager requests

      - name: Run Scraper
        run: python scraper.py

      - name: Auto-Save CSV
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update tender list"
          file_pattern: 'tenders.csv'

      - name: Upload Bid Documents
        uses: actions/upload-artifact@v4
        with:
          name: Rajasthan-Bid-Docs
          path: bid_documents/
          retention-days: 7 # Kept for 7 days for free
